remaining-time-format: '%days% days %hours% hours %minutes% minutes %seconds% seconds'
next-event-time-format: dd/MM hh:mma
dragon-event-time: 15 # minutes
event-price: 500
price-required-for-every-join: true # if true, players will pay every time when they join an event
                                    # like rejoining after leaving with /dragon leave
lobby-world-name: world
event-world-name: 'dragonevent_end'

auto-start:
  enabled: true
  max-per-month: 100
  timezone: 'GMT+3'

  days:
    Sunday:
      times: 01:15AM, 12:05PM, 08:00PM

    Monday:
      times: 01:15AM, 12:05PM, 08:00PM

    Tuesday:
      times: 01:15AM, 12:05PM, 08:00PM

    Wednesday:
      times: 01:15AM, 12:05PM, 08:00PM

    Thursday:
      times: 01:15AM, 12:05PM, 08:00PM

    Friday:
      times: 01:15AM, 12:05PM, 08:00PM

    Saturday:
      times: 01:15AM, 12:05PM, 08:00PM

dragon:
  name: "&aEvent Dragon"
  required-kills: 4 # they would need to kill dragons 4 times in order for event to end
  glow: true
  glow-color: RED # possible colors: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE,
                  #                  GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
  # Max 200
  health: 200

end-rules:
  disable-pvp: true
  keepInventory: true
  announceAdvancements: false
  showDeathMessages: false

# Discord feature
discord:
  enabled: false
  # Bot token
  token: ''
  # Text channel id
  channel-id: ''
  embeds:
    timer:
      message: '<@&roleid>'
      title: "Dragon Event Starting Soon"
      description: "Dragon Event Starting Soon <t:%timestamp%:R>"
      color: 38f295
      footer:
        icon-url: "https://img001.prntscr.com/file/img001/YUVatsHGTl-5THs-SOa7ZA.png"
        text: "MCServer"
    start:
      message: '<@&roleid>'
      title: "Dragon Event Started"
      description: "Jump into the portal in spawn to enter the event."
      color: 38f295
      footer:
        icon-url: "https://img001.prntscr.com/file/img001/YUVatsHGTl-5THs-SOa7ZA.png"
        text: "MCServer"
    end:
      message: '<@&roleid>'
      title: "Dragon Event Ended"
      description: "Thanks for joining!"
      color: 38f295
      footer:
        icon-url: "https://img001.prntscr.com/file/img001/YUVatsHGTl-5THs-SOa7ZA.png"
        text: "MCServer"

commands:
  start:
    - ""
  end:
    - ""

messages:
  start:
    - '&f #81e0f7Dragon Event has just started! Jump into the portal in spawn to join!'
  end:
    - "&8&m---------------------------------------"
    - "&a&lEvent Dragon Killed! Damage Leaderboard:"
    - " "
    - "&f &aFirst &d%dragonevent_top_damage_name_1% &7- &d%dragonevent_top_damage_damage_1%"
    - "&f &aSecond &d%dragonevent_top_damage_name_2% &7- &d%dragonevent_top_damage_damage_2%"
    - "&f &aThird &d%dragonevent_top_damage_name_3% &7- &d%dragonevent_top_damage_damage_3%"
    - " "
    - "&a&lTop 3 Prizes"
    - " "
    - "&f &21x &aDragon Egg &8- &23x &aDragon Head"
    - "&f &22x &aDragon Head"
    - "&f &21x &aDragon Head"
    - " "
    - "&8&m---------------------------------------"
  timed-out: '&aEvent Dragon was not killed in time so nobody won.'
  no-perm: '&cI''m sorry but you can not do that.'
  not-active: '&cEvent has not started yet.'
  force-start: '&aA staff member started Dragon Event.'
  force-stop: '&aA staff member ended Dragon Event.'
  went-wrong: '&cSomething went wrong while trying to join the event. Please let staff members know about this.'
  already-playing: '&cYou are already in the event.'
  not-playing: '&cYou are not in the event.'
  joined: '&aYou joined Dragon Event!'
  left-event: '&cYou just left Dragon Event.'
  leaderboard-empty-entry: '&dEmpty'

  no-arguments: '&b/dragonadmin reload|save|start|stop'
  reloaded: '&bConfig reloaded!'
  saved: '&bSpawn and auto save data are saved!'
  new-spawn: '&bNew spawn location: &f%location%'
  spawn-not-set: '&cSpawn location is not set, therefore Dragon Event can not be started.'

sounds:
  start:
    enable: true
    sound: 'ENTITY_LIGHTNING_BOLT_THUNDER'
  end:
    enable: true
    sound: 'ENTITY_LIGHTNING_BOLT_THUNDER'

titles:
  start:
    enable: true
    title: '#81e0f7&lDragon Event'
    subTitle: '&aStarting...'
  end:
    enable: true
    title: '#81e0f7Dragon Event'
    subTitle: '&cEnding...'
  respawn:
    enable: true
    title: '&bDRAGON SUDDENLY REBORN!'
    subTitle: '&eYou have to kill it &9%times% times &emore!'

endgame-commands:

  places:
    1:
      - 'give %player_name% dragon_egg 1'
      - 'give %player_name% dragon_head 3'
    2:
      - 'give %player_name% dragon_head 2'
    3:
      - 'give %player_name% dragon_head 1'

  every-other-player:
    - 'bal add %player_name% 1000'